"""M01 foundation schema.

Revision ID: 20250827_01
Revises:
Create Date: 2026-08-27
"""

import re
from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20250827_01"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None

_SCHEMA_SQL = r"""
CREATE TYPE exception_type AS ENUM ('SLA_BREACH_RISK', 'INVENTORY_SHORTAGE', 'STOCKOUT_RISK', 'INVENTORY_MISMATCH', 'SUPPLIER_DELAY', 'SHIPMENT_DELAY');

CREATE TYPE exception_severity AS ENUM ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW');

CREATE TYPE exception_status AS ENUM ('OPEN', 'ACKNOWLEDGED', 'IN_PROGRESS', 'RESOLVED', 'DISMISSED');

CREATE TYPE order_status AS ENUM ('OPEN', 'FULFILLED', 'CANCELLED');

CREATE TYPE purchase_order_status AS ENUM ('OPEN', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED');

CREATE TYPE shipment_status AS ENUM ('CREATED', 'IN_TRANSIT', 'DELIVERED', 'EXCEPTION');

CREATE TYPE inventory_movement_type AS ENUM ('RECEIPT', 'SHIPMENT', 'ADJUSTMENT_IN', 'ADJUSTMENT_OUT', 'RESERVATION', 'RELEASE', 'TRANSFER_IN', 'TRANSFER_OUT');

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    source_product_id VARCHAR(100) NOT NULL,
    sku VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    unit_price NUMERIC(14, 2) NOT NULL,
    active BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT ck_products_unit_price_non_negative CHECK (unit_price >= 0),
    CONSTRAINT uq_products_source_product_id UNIQUE (source_product_id),
    CONSTRAINT uq_products_sku UNIQUE (sku)
);

CREATE INDEX ix_products_sku ON products (sku);

CREATE TABLE suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    source_supplier_id VARCHAR(100) NOT NULL,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    region VARCHAR(100) NOT NULL,
    active BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_suppliers PRIMARY KEY (id),
    CONSTRAINT uq_suppliers_source_supplier_id UNIQUE (source_supplier_id),
    CONSTRAINT uq_suppliers_code UNIQUE (code)
);

CREATE TABLE warehouses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    source_warehouse_id VARCHAR(100) NOT NULL,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    region VARCHAR(100) NOT NULL,
    timezone VARCHAR(64) DEFAULT 'UTC' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_warehouses PRIMARY KEY (id),
    CONSTRAINT uq_warehouses_source_warehouse_id UNIQUE (source_warehouse_id),
    CONSTRAINT uq_warehouses_code UNIQUE (code)
);




CREATE TABLE exceptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    deduplication_key VARCHAR(255) NOT NULL,
    exception_type exception_type NOT NULL,
    issue_key VARCHAR(255) NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id VARCHAR(128) NOT NULL,
    severity exception_severity NOT NULL,
    status exception_status NOT NULL,
    detected_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expected_resolution TIMESTAMP WITH TIME ZONE,
    business_impact TEXT NOT NULL,
    revenue_at_risk NUMERIC(14, 2) DEFAULT 0 NOT NULL,
    orders_affected INTEGER DEFAULT 0 NOT NULL,
    root_cause TEXT NOT NULL,
    recommended_action TEXT NOT NULL,
    confidence NUMERIC(5, 4) NOT NULL,
    warehouse_id BIGINT,
    product_id BIGINT,
    resolved_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_exceptions PRIMARY KEY (id),
    CONSTRAINT fk_exceptions_product_id_products FOREIGN KEY(product_id) REFERENCES products (id) ON DELETE SET NULL,
    CONSTRAINT ck_exceptions_revenue_at_risk_non_negative CHECK (revenue_at_risk >= 0),
    CONSTRAINT ck_exceptions_orders_affected_non_negative CHECK (orders_affected >= 0),
    CONSTRAINT ck_exceptions_confidence_0_1 CHECK (confidence >= 0 AND confidence <= 1),
    CONSTRAINT fk_exceptions_warehouse_id_warehouses FOREIGN KEY(warehouse_id) REFERENCES warehouses (id) ON DELETE SET NULL,
    CONSTRAINT uq_exceptions_deduplication_key UNIQUE (deduplication_key)
);

CREATE INDEX ix_exceptions_status_detected_at ON exceptions (status, detected_at);

CREATE INDEX ix_exceptions_warehouse_status ON exceptions (warehouse_id, status);

CREATE UNIQUE INDEX uq_exceptions_active_type_issue_key ON exceptions (exception_type, issue_key) WHERE status IN ('OPEN', 'ACKNOWLEDGED', 'IN_PROGRESS');

CREATE TABLE inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL,
    on_hand NUMERIC(18, 3) NOT NULL,
    reserved NUMERIC(18, 3) NOT NULL,
    available NUMERIC(18, 3) GENERATED ALWAYS AS (on_hand - reserved) STORED NOT NULL,
    observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_inventory PRIMARY KEY (id),
    CONSTRAINT fk_inventory_warehouse_id_warehouses FOREIGN KEY(warehouse_id) REFERENCES warehouses (id) ON DELETE RESTRICT,
    CONSTRAINT fk_inventory_product_id_products FOREIGN KEY(product_id) REFERENCES products (id) ON DELETE RESTRICT,
    CONSTRAINT ck_inventory_reserved_non_negative CHECK (reserved >= 0),
    CONSTRAINT ck_inventory_on_hand_non_negative CHECK (on_hand >= 0),
    CONSTRAINT uq_inventory_product_warehouse UNIQUE (product_id, warehouse_id)
);

CREATE INDEX ix_inventory_warehouse_product ON inventory (warehouse_id, product_id);


CREATE TABLE inventory_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    source_movement_id VARCHAR(100) NOT NULL,
    product_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL,
    movement_type inventory_movement_type NOT NULL,
    quantity NUMERIC(18, 3) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    reference_type VARCHAR(50),
    reference_id VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_inventory_movements PRIMARY KEY (id),
    CONSTRAINT ck_inventory_movements_quantity_positive CHECK (quantity > 0),
    CONSTRAINT fk_inventory_movements_warehouse_id_warehouses FOREIGN KEY(warehouse_id) REFERENCES warehouses (id) ON DELETE RESTRICT,
    CONSTRAINT fk_inventory_movements_product_id_products FOREIGN KEY(product_id) REFERENCES products (id) ON DELETE RESTRICT,
    CONSTRAINT uq_inventory_movements_source_movement_id UNIQUE (source_movement_id)
);

CREATE INDEX ix_inventory_movements_product_warehouse_occurred ON inventory_movements (product_id, warehouse_id, occurred_at);


CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    source_order_id VARCHAR(100) NOT NULL,
    order_number VARCHAR(100) NOT NULL,
    status order_status NOT NULL,
    region VARCHAR(100) NOT NULL,
    warehouse_id BIGINT NOT NULL,
    ordered_at TIMESTAMP WITH TIME ZONE NOT NULL,
    promised_at TIMESTAMP WITH TIME ZONE NOT NULL,
    fulfilled_at TIMESTAMP WITH TIME ZONE,
    total_amount NUMERIC(14, 2) NOT NULL,
    currency VARCHAR(3) DEFAULT 'USD' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT ck_orders_fulfilled_after_ordered CHECK (fulfilled_at IS NULL OR fulfilled_at >= ordered_at),
    CONSTRAINT ck_orders_total_amount_non_negative CHECK (total_amount >= 0),
    CONSTRAINT fk_orders_warehouse_id_warehouses FOREIGN KEY(warehouse_id) REFERENCES warehouses (id) ON DELETE RESTRICT,
    CONSTRAINT uq_orders_order_number UNIQUE (order_number),
    CONSTRAINT uq_orders_source_order_id UNIQUE (source_order_id)
);

CREATE INDEX ix_orders_status_promised_at ON orders (status, promised_at);

CREATE INDEX ix_orders_warehouse_status ON orders (warehouse_id, status);


CREATE TABLE purchase_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    source_purchase_order_id VARCHAR(100) NOT NULL,
    po_number VARCHAR(100) NOT NULL,
    supplier_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL,
    status purchase_order_status NOT NULL,
    ordered_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expected_delivery_at TIMESTAMP WITH TIME ZONE NOT NULL,
    received_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_purchase_orders PRIMARY KEY (id),
    CONSTRAINT fk_purchase_orders_supplier_id_suppliers FOREIGN KEY(supplier_id) REFERENCES suppliers (id) ON DELETE RESTRICT,
    CONSTRAINT fk_purchase_orders_warehouse_id_warehouses FOREIGN KEY(warehouse_id) REFERENCES warehouses (id) ON DELETE RESTRICT,
    CONSTRAINT ck_purchase_orders_received_after_ordered CHECK (received_at IS NULL OR received_at >= ordered_at),
    CONSTRAINT uq_purchase_orders_po_number UNIQUE (po_number),
    CONSTRAINT uq_purchase_orders_source_purchase_order_id UNIQUE (source_purchase_order_id)
);

CREATE INDEX ix_purchase_orders_status_expected_delivery ON purchase_orders (status, expected_delivery_at);

CREATE TABLE exception_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    exception_id BIGINT NOT NULL,
    from_status exception_status,
    to_status exception_status NOT NULL,
    changed_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    actor VARCHAR(100) NOT NULL,
    transition_reason TEXT,
    CONSTRAINT pk_exception_history PRIMARY KEY (id),
    CONSTRAINT fk_exception_history_exception_id_exceptions FOREIGN KEY(exception_id) REFERENCES exceptions (id) ON DELETE CASCADE
);

CREATE INDEX ix_exception_history_exception_changed ON exception_history (exception_id, changed_at);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    source_order_item_id VARCHAR(120) NOT NULL,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    line_number INTEGER NOT NULL,
    ordered_quantity NUMERIC(18, 3) NOT NULL,
    fulfilled_quantity NUMERIC(18, 3) NOT NULL,
    unit_price NUMERIC(14, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (id),
    CONSTRAINT ck_order_items_ordered_quantity_positive CHECK (ordered_quantity > 0),
    CONSTRAINT fk_order_items_order_id_orders FOREIGN KEY(order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT ck_order_items_fulfilled_quantity_lte_ordered_quantity CHECK (fulfilled_quantity <= ordered_quantity),
    CONSTRAINT ck_order_items_unit_price_non_negative CHECK (unit_price >= 0),
    CONSTRAINT ck_order_items_fulfilled_quantity_non_negative CHECK (fulfilled_quantity >= 0),
    CONSTRAINT fk_order_items_product_id_products FOREIGN KEY(product_id) REFERENCES products (id) ON DELETE RESTRICT,
    CONSTRAINT uq_order_items_source_order_item_id UNIQUE (source_order_item_id),
    CONSTRAINT uq_order_items_order_line UNIQUE (order_id, line_number)
);

CREATE TABLE purchase_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    source_purchase_order_item_id VARCHAR(120) NOT NULL,
    purchase_order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    ordered_quantity NUMERIC(18, 3) NOT NULL,
    received_quantity NUMERIC(18, 3) NOT NULL,
    unit_cost NUMERIC(14, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_purchase_order_items PRIMARY KEY (id),
    CONSTRAINT fk_purchase_order_items_product_id_products FOREIGN KEY(product_id) REFERENCES products (id) ON DELETE RESTRICT,
    CONSTRAINT fk_purchase_order_items_purchase_order_id_purchase_orders FOREIGN KEY(purchase_order_id) REFERENCES purchase_orders (id) ON DELETE CASCADE,
    CONSTRAINT ck_purchase_order_items_received_quantity_non_negative CHECK (received_quantity >= 0),
    CONSTRAINT ck_purchase_order_items_unit_cost_non_negative CHECK (unit_cost >= 0),
    CONSTRAINT ck_purchase_order_items_received_quantity_lte_ordered_quantity CHECK (received_quantity <= ordered_quantity),
    CONSTRAINT ck_purchase_order_items_ordered_quantity_positive CHECK (ordered_quantity > 0),
    CONSTRAINT uq_purchase_order_items_source_purchase_order_item_id UNIQUE (source_purchase_order_item_id)
);


CREATE TABLE shipments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    source_shipment_id VARCHAR(100) NOT NULL,
    order_id BIGINT NOT NULL,
    carrier VARCHAR(100) NOT NULL,
    tracking_id VARCHAR(150) NOT NULL,
    status shipment_status NOT NULL,
    shipped_at TIMESTAMP WITH TIME ZONE,
    eta TIMESTAMP WITH TIME ZONE NOT NULL,
    delivered_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_shipments PRIMARY KEY (id),
    CONSTRAINT fk_shipments_order_id_orders FOREIGN KEY(order_id) REFERENCES orders (id) ON DELETE RESTRICT,
    CONSTRAINT ck_shipments_delivered_after_shipped CHECK (delivered_at IS NULL OR shipped_at IS NULL OR delivered_at >= shipped_at),
    CONSTRAINT uq_shipments_tracking_id UNIQUE (tracking_id),
    CONSTRAINT uq_shipments_source_shipment_id UNIQUE (source_shipment_id)
);

CREATE INDEX ix_shipments_status_eta ON shipments (status, eta);
"""


def upgrade() -> None:
    """Create the empty PostgreSQL schema for M01."""

    # A raw PostgreSQL snapshot keeps enum creation deterministic and avoids
    # relying on model-side DDL event ordering in an initial migration.
    for statement in re.split(r";\s*\n", _SCHEMA_SQL):
        if statement.strip():
            op.execute(sa.text(statement.strip() + ";"))


def downgrade() -> None:
    """Remove the M01 schema in dependency-safe order."""

    for table_name in (
        "exception_history",
        "shipments",
        "purchase_order_items",
        "order_items",
        "purchase_orders",
        "orders",
        "inventory_movements",
        "inventory",
        "exceptions",
        "warehouses",
        "suppliers",
        "products",
    ):
        op.execute(sa.text(f"DROP TABLE IF EXISTS {table_name}"))
    for type_name in (
        "inventory_movement_type",
        "shipment_status",
        "purchase_order_status",
        "order_status",
        "exception_status",
        "exception_severity",
        "exception_type",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {type_name}"))
