"""Add source-scoped immutable order observations and projection receipts.

Revision ID: 20260911_01
Revises: 20250827_02
Create Date: 2026-09-11
"""

from typing import Sequence

from alembic import op

revision: str = "20260911_01"
down_revision: str | None = "20250827_02"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None

_STATUS_TYPE = "order_observation_status"


def upgrade() -> None:
    """Create immutable evidence tables and namespace-aware Order linkage."""
    op.execute(
        f"""
        CREATE TYPE {_STATUS_TYPE} AS ENUM (
            'SOURCE_VALID', 'NORMALIZED', 'CONTEXT_INCOMPLETE', 'PROMOTED',
            'REJECTED_INVALID', 'CONFLICT_BLOCKED'
        )
        """
    )

    # Existing orders remain valid without invented source identity or version.
    op.execute("ALTER TABLE orders ADD COLUMN source_namespace VARCHAR(100)")
    op.execute("ALTER TABLE orders ADD COLUMN source_order_identity_id BIGINT")
    op.execute("ALTER TABLE orders ADD COLUMN projected_source_version VARCHAR(100)")
    op.execute("ALTER TABLE orders ADD COLUMN source_warehouse_id VARCHAR(100)")
    op.execute("ALTER TABLE orders ADD COLUMN current_observation_id BIGINT")
    op.execute("ALTER TABLE orders DROP CONSTRAINT uq_orders_order_number")
    op.execute("ALTER TABLE orders DROP CONSTRAINT uq_orders_source_order_id")

    op.execute(
        """
        CREATE TABLE source_order_identities (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            source_namespace VARCHAR(100) NOT NULL,
            source_order_id VARCHAR(100) NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
            CONSTRAINT pk_source_order_identities PRIMARY KEY (id),
            CONSTRAINT uq_source_order_identity_namespace_order
                UNIQUE (source_namespace, source_order_id)
        )
        """
    )
    op.execute(
        """
        ALTER TABLE orders
        ADD CONSTRAINT fk_orders_source_order_identity_id_source_order_identities
        FOREIGN KEY (source_order_identity_id)
        REFERENCES source_order_identities (id) ON DELETE RESTRICT
        """
    )
    op.execute(
        """
        ALTER TABLE orders
        ADD CONSTRAINT uq_orders_source_namespace_order
            UNIQUE (source_namespace, source_order_id),
        ADD CONSTRAINT uq_orders_source_namespace_number
            UNIQUE (source_namespace, order_number)
        """
    )

    op.execute(
        f"""
        CREATE TABLE order_observations (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            source_order_identity_id BIGINT NOT NULL,
            source_namespace VARCHAR(100) NOT NULL,
            source_order_id VARCHAR(100) NOT NULL,
            source_version VARCHAR(100),
            source_row_hash VARCHAR(64) NOT NULL,
            replay_identity JSONB NOT NULL,
            replay_identity_digest VARCHAR(64) NOT NULL,
            source_facts JSONB NOT NULL,
            order_number VARCHAR(100),
            order_status order_status,
            region VARCHAR(100),
            source_warehouse_id VARCHAR(100),
            warehouse_id BIGINT,
            ordered_at TIMESTAMP WITH TIME ZONE,
            promised_at TIMESTAMP WITH TIME ZONE,
            fulfilled_at TIMESTAMP WITH TIME ZONE,
            total_amount NUMERIC(14, 2),
            currency VARCHAR(3),
            status {_STATUS_TYPE} NOT NULL,
            source_status {_STATUS_TYPE} NOT NULL,
            capabilities JSONB NOT NULL,
            non_promotion_reasons JSONB NOT NULL,
            promoted_order_id BIGINT,
            superseded_by_observation_id BIGINT,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
            CONSTRAINT pk_order_observations PRIMARY KEY (id),
            CONSTRAINT uq_order_observations_replay_identity_digest
                UNIQUE (replay_identity_digest),
            CONSTRAINT fk_order_observations_source_order_identity_id_source_order_identities
                FOREIGN KEY (source_order_identity_id)
                REFERENCES source_order_identities (id) ON DELETE RESTRICT,
            CONSTRAINT fk_order_observations_promoted_order_id
                FOREIGN KEY (promoted_order_id) REFERENCES orders (id) ON DELETE RESTRICT,
            CONSTRAINT fk_order_observations_warehouse_id
                FOREIGN KEY (warehouse_id) REFERENCES warehouses (id) ON DELETE RESTRICT,
            CONSTRAINT fk_order_observations_superseded_by_observation_id
                FOREIGN KEY (superseded_by_observation_id)
                REFERENCES order_observations (id) ON DELETE RESTRICT,
            CONSTRAINT order_observations_total_amount_non_negative
                CHECK (total_amount IS NULL OR total_amount >= 0),
            CONSTRAINT order_observations_fulfilled_after_ordered
                CHECK (
                    fulfilled_at IS NULL OR ordered_at IS NULL OR fulfilled_at >= ordered_at
                )
        )
        """
    )
    op.execute(
        """
        ALTER TABLE orders
        ADD CONSTRAINT fk_orders_current_observation_id_order_observations
        FOREIGN KEY (current_observation_id)
        REFERENCES order_observations (id) ON DELETE RESTRICT
        """
    )
    op.execute("CREATE INDEX ix_order_observations_status ON order_observations (status)")
    op.execute(
        "CREATE INDEX ix_order_observations_source_order "
        "ON order_observations (source_namespace, source_order_id)"
    )
    op.execute(
        "CREATE INDEX ix_order_observations_source_version "
        "ON order_observations (source_order_identity_id, source_version)"
    )

    op.execute(
        """
        CREATE TABLE order_observation_receipts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            observation_id BIGINT NOT NULL,
            batch_id VARCHAR(128) NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
            CONSTRAINT pk_order_observation_receipts PRIMARY KEY (id),
            CONSTRAINT fk_order_observation_receipts_observation_id_order_observations
                FOREIGN KEY (observation_id)
                REFERENCES order_observations (id) ON DELETE RESTRICT,
            CONSTRAINT uq_order_observation_receipt_observation_batch
                UNIQUE (observation_id, batch_id)
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_order_observation_receipts_batch ON order_observation_receipts (batch_id)"
    )

    # Evidence columns are immutable at the database boundary. Lifecycle and
    # currentness columns remain intentionally mutable for promotion workflow.
    op.execute(
        """
        CREATE FUNCTION reject_order_observation_evidence_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF TG_OP = 'DELETE' THEN
                RAISE EXCEPTION 'order_observation evidence is append-only';
            END IF;
            IF OLD.source_order_identity_id IS DISTINCT FROM NEW.source_order_identity_id
                OR OLD.source_namespace IS DISTINCT FROM NEW.source_namespace
                OR OLD.source_order_id IS DISTINCT FROM NEW.source_order_id
                OR OLD.source_version IS DISTINCT FROM NEW.source_version
                OR OLD.source_row_hash IS DISTINCT FROM NEW.source_row_hash
                OR OLD.replay_identity IS DISTINCT FROM NEW.replay_identity
                OR OLD.replay_identity_digest IS DISTINCT FROM NEW.replay_identity_digest
                OR OLD.source_facts IS DISTINCT FROM NEW.source_facts
                OR OLD.order_number IS DISTINCT FROM NEW.order_number
                OR OLD.order_status IS DISTINCT FROM NEW.order_status
                OR OLD.region IS DISTINCT FROM NEW.region
                OR OLD.source_warehouse_id IS DISTINCT FROM NEW.source_warehouse_id
                OR OLD.ordered_at IS DISTINCT FROM NEW.ordered_at
                OR OLD.promised_at IS DISTINCT FROM NEW.promised_at
                OR OLD.fulfilled_at IS DISTINCT FROM NEW.fulfilled_at
                OR OLD.total_amount IS DISTINCT FROM NEW.total_amount
                OR OLD.currency IS DISTINCT FROM NEW.currency
            THEN
                RAISE EXCEPTION 'order_observation evidence is immutable';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER order_observations_evidence_immutable
        BEFORE UPDATE OR DELETE ON order_observations
        FOR EACH ROW EXECUTE FUNCTION reject_order_observation_evidence_mutation()
        """
    )


def downgrade() -> None:
    """Remove evidence in dependency order, then restore legacy constraints."""
    op.execute("DROP TRIGGER order_observations_evidence_immutable ON order_observations")
    op.execute("DROP FUNCTION reject_order_observation_evidence_mutATION()")

    op.execute(
        "ALTER TABLE orders DROP CONSTRAINT fk_orders_current_observation_id_order_observations"
    )
    op.execute(
        "ALTER TABLE orders DROP CONSTRAINT "
        "fk_orders_source_order_identity_id_source_order_identities"
    )
    op.execute(
        "ALTER TABLE order_observation_receipts DROP CONSTRAINT "
        "fk_order_observation_receipts_observation_id_order_observations"
    )
    op.execute(
        "ALTER TABLE order_observations DROP CONSTRAINT "
        "fk_order_observations_superseded_by_observation_id"
    )
    op.execute("ALTER TABLE order_observations DROP CONSTRAINT fk_order_observations_warehouse_id")
    op.execute(
        "ALTER TABLE order_observations DROP CONSTRAINT fk_order_observations_promoted_order_id"
    )
    op.execute(
        "ALTER TABLE order_observations DROP CONSTRAINT "
        "fk_order_observations_source_order_identity_id_source_order_identities"
    )

    op.execute("DROP TABLE order_observation_receipts")
    op.execute("DROP TABLE order_observations")
    op.execute("DROP TABLE source_order_identities")

    op.execute("ALTER TABLE orders DROP CONSTRAINT uq_orders_source_namespace_number")
    op.execute("ALTER TABLE orders DROP CONSTRAINT uq_orders_source_namespace_order")
    op.execute("ALTER TABLE orders DROP COLUMN current_observation_id")
    op.execute("ALTER TABLE orders DROP COLUMN source_warehouse_id")
    op.execute("ALTER TABLE orders DROP COLUMN projected_source_version")
    op.execute("ALTER TABLE orders DROP COLUMN source_order_identity_id")
    op.execute("ALTER TABLE orders DROP COLUMN source_namespace")
    op.execute("ALTER TABLE orders ADD CONSTRAINT uq_orders_order_number UNIQUE (order_number)")
    op.execute(
        "ALTER TABLE orders ADD CONSTRAINT uq_orders_source_order_id UNIQUE (source_order_id)"
    )
    op.execute(f"DROP TYPE {_STATUS_TYPE}")
